# -*- coding: utf-8 -*-
"""iot_assignment2.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugZ-IPyncJfYQDtohFuFZaJGX5H-_dq-
"""

from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import initializers
import matplotlib.pyplot as plt

data = np.loadtxt( "IOT_Assignment_2_data_regression_sensor_range.csv",dtype=float , delimiter=',')
# data.shape

data_trn, data_tst = train_test_split( data, test_size= 0.3)
humid_temp_trn, water_trn = data_trn[:,:2], data_trn[:,2]
humid_temp_tst,water_tst = data_tst[:,:2],data_tst[:,2]
# data_tst

model = Sequential([    
      # input layer
    Dense(256, input_shape=(2,),kernel_initializer=initializers.RandomNormal(stddev=0.01),activation='relu'),
      # dense layer 1
    Dense(256, activation='relu'),     
    # dense layer 2
    Dense(256, activation='relu'),    
      # output layer
    Dense(1, activation='relu'),  
])

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'], )

model.fit(humid_temp_trn, water_trn, verbose=2, epochs=10,batch_size=10)

water_pred=model.predict(humid_temp_tst)

print(humid_temp_trn)

plt.plot(np.arange(water_tst.size),water_tst,color='red')
plt.plot(np.arange(water_pred.size), water_pred,color='blue')

model.predict([[27.5,96]])

